name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn run test
